twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig', '@collection/jquery.collection.html.twig']
    paths:
        '%kernel.project_dir%/vendor/ninsuo/symfony-collection': collection
